INSERT INTO estado (id_estado, nome, sigla) VALUES(99, 'Ignorado/exterior', 'IG');
INSERT INTO estado (id_estado, nome, sigla) VALUES(24, 'Rio Grande do Norte', 'RN');
INSERT INTO estado (id_estado, nome, sigla) VALUES(11, 'Rondônia', 'RO');
INSERT INTO estado (id_estado, nome, sigla) VALUES(12, 'Acre', 'AC');

INSERT INTO cidade (id_estado, nome) VALUES(24, 'Natal');
INSERT INTO cidade (id_estado, nome) VALUES(12, 'Acrelândia');
INSERT INTO cidade (id_estado, nome) VALUES(12, 'Assis Brasil');
INSERT INTO cidade (id_estado, nome) VALUES(12, 'Brasiléia');
INSERT INTO cidade (id_estado, nome) VALUES(12, 'Bujari');
INSERT INTO cidade (id_estado, nome) VALUES(12, 'Capixaba');
INSERT INTO cidade (id_estado, nome) VALUES(12, 'Cruzeiro do Sul');
INSERT INTO cidade (id_estado, nome) VALUES(12, 'Epitaciolândia');
INSERT INTO cidade (id_estado, nome) VALUES(12, 'Feijó');
INSERT INTO cidade (id_estado, nome) VALUES(12, 'Jordão');
INSERT INTO cidade (id_estado, nome) VALUES(12, 'Mâncio Lima');
INSERT INTO cidade (id_estado, nome) VALUES(12, 'Manoel Urbano');
INSERT INTO cidade (id_estado, nome) VALUES(12, 'Marechal Thaumaturgo');
INSERT INTO cidade (id_estado, nome) VALUES(12, 'Plácido de Castro');
INSERT INTO cidade (id_estado, nome) VALUES(12, 'Porto Acre');
INSERT INTO cidade (id_estado, nome) VALUES(12, 'Porto Walter');
INSERT INTO cidade (id_estado, nome) VALUES(12, 'Rio Branco');
INSERT INTO cidade (id_estado, nome) VALUES(12, 'Rodrigues Alves');
INSERT INTO cidade (id_estado, nome) VALUES(12, 'Santa Rosa');
INSERT INTO cidade (id_estado, nome) VALUES(12, 'Sena Madureira');
INSERT INTO cidade (id_estado, nome) VALUES(12, 'Senador Guiomard');
INSERT INTO cidade (id_estado, nome) VALUES(12, 'Tarauacá');
INSERT INTO cidade (id_estado, nome) VALUES(12, 'Xapuri');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Acari');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Açu');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Afonso Bezerra');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Água Nova');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Alexandria');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Almino Afonso');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Alto do Rodrigues');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Angicos');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Antônio Martins');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Apodi');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Areia Branca');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Arez');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Baía Formosa');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Barão de Serra Branca');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Baraúna');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Barcelona');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Belo Horizonte');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Bento Fernandes');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Boa Saúde');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Bodó');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Bom Jesus');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Brejinho');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Caiçara do Norte');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Caiçara do Rio do Vento');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Caicó');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Campo Grande');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Campo Redondo');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Canguaretama');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Caraúbas');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Carnaúba dos Dantas');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Carnaubais');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Ceará-Mirim');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Cerro Corá');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Coronel Ezequiel');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Coronel João Pessoa');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Córrego de São Mateus');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Cruzeta');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Currais Novos');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Doutor Severiano');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Encanto');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Equador');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Espírito Santo');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Paraú');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Extremoz');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Felipe Guerra');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Fernando Pedroza');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Firmamento');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Florânia');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Francisco Dantas');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Frutuoso Gomes');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Galinhos');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Gameleira');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Goianinha');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Governador Dix-Sept Rosado');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Grossos');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Guamaré');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Ielmo Marinho');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Igreja Nova');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Ipanguaçu');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Ipiranga');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Ipueira');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Itajá');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Itaú');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Jaçanã');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Jandaíra');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Janduís');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Japi');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Jardim de Angicos');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Jardim de Piranhas');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Jardim do Seridó');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'João Câmara');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'João Dias');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'José da Penha');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Jucurutu');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Jundiá');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Lagoa D''Anta');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Lagoa de Pedras');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Lagoa de Velhos');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Lagoa Nova');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Lagoa Salgada');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Lajes');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Lajes Pintadas');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Lucrécia');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Luís Gomes');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Macaíba');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Macau');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Major Felipe');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Major Sales');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Marcelino Vieira');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Martins');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Mata de São Braz');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Maxaranguape');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Messias Targino');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Montanhas');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Monte Alegre');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Monte das Gameleiras');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Mossoró');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Nísia Floresta');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Nova Cruz');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Olho-D''Água do Borges');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Ouro Branco');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Paraná');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Parazinho');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Parelhas');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Parnamirim');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Passa e Fica');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Passagem');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Patu');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Pau dos Ferros');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Pedra Grande');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Pedra Preta');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Pedro Avelino');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Pedro Velho');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Pendências');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Pilões');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Poço Branco');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Portalegre');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Porto do Mangue');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Pureza');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Rafael Fernandes');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Rafael Godeiro');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Riacho da Cruz');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Riacho de Santana');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Riachuelo');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Rio do Fogo');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Rodolfo Fernandes');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Rosário');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Ruy Barbosa');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Salva Vida');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Santa Cruz');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Santa Fé');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Santa Maria');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Santa Teresa');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Santana do Matos');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Santana do Seridó');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Santo Antônio');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Santo Antônio do Potengi');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'São Bento do Norte');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'São Bento do Trairi');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'São Bernardo');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'São Fernando');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'São Francisco do Oeste');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'São Geraldo');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'São Gonçalo do Amarante');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'São João do Sabugi');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'São José da Passagem');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'São José de Mipibu');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'São José do Campestre');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'São José do Seridó');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'São Miguel');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'São Miguel de Touros');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'São Paulo do Potengi');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'São Pedro');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'São Rafael');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'São Tomé');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'São Vicente');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Senador Elói de Souza');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Senador Georgino Avelino');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Serra Caiada');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Serra da Tapuia');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Serra de São Bento');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Serra do Mel');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Serra Negra do Norte');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Serrinha');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Serrinha dos Pintos');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Severiano Melo');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Sítio Novo');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Taboleiro Grande');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Taipu');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Tangará');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Tenente Ananias');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Tenente Laurentino Cruz');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Tibau');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Tibau do Sul');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Timbaúba dos Batistas');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Touros');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Trairi');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Triunfo Potiguar');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Umarizal');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Upanema');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Várzea');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Venha-Ver');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Vera Cruz');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Viçosa');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'Vila Flor');
INSERT INTO cidade (id_estado, nome) VALUES(11, 'Abunã');
INSERT INTO cidade (id_estado, nome) VALUES(11, 'Alto Alegre dos Parecis');
INSERT INTO cidade (id_estado, nome) VALUES(11, 'Alta Floresta do Oeste');
INSERT INTO cidade (id_estado, nome) VALUES(11, 'Alto Paraíso');
INSERT INTO cidade (id_estado, nome) VALUES(11, 'Alvorada D''Oeste');
INSERT INTO cidade (id_estado, nome) VALUES(11, 'Ariquemes');
INSERT INTO cidade (id_estado, nome) VALUES(11, 'Buritis');
INSERT INTO cidade (id_estado, nome) VALUES(11, 'Cabixi');
INSERT INTO cidade (id_estado, nome) VALUES(11, 'Cacaulândia');
INSERT INTO cidade (id_estado, nome) VALUES(11, 'Cacoal');
INSERT INTO cidade (id_estado, nome) VALUES(11, 'Calama');
INSERT INTO cidade (id_estado, nome) VALUES(11, 'Campo Novo de Rondônia');
INSERT INTO cidade (id_estado, nome) VALUES(11, 'Candeias do Jamari');
INSERT INTO cidade (id_estado, nome) VALUES(11, 'Castanheiras');
INSERT INTO cidade (id_estado, nome) VALUES(11, 'Cerejeiras');
INSERT INTO cidade (id_estado, nome) VALUES(11, 'Chupinguaia');
INSERT INTO cidade (id_estado, nome) VALUES(11, 'Colorado do Oeste');
INSERT INTO cidade (id_estado, nome) VALUES(11, 'Corumbiara');
INSERT INTO cidade (id_estado, nome) VALUES(11, 'Costa Marques');
INSERT INTO cidade (id_estado, nome) VALUES(11, 'Cujubim');
INSERT INTO cidade (id_estado, nome) VALUES(11, 'Espigão D''Oeste');
INSERT INTO cidade (id_estado, nome) VALUES(11, 'Governador Jorge Teixeira');
INSERT INTO cidade (id_estado, nome) VALUES(11, 'Guajará-Mirim');
INSERT INTO cidade (id_estado, nome) VALUES(11, 'Jaci Paraná');
INSERT INTO cidade (id_estado, nome) VALUES(11, 'Itapuã do Oeste');
INSERT INTO cidade (id_estado, nome) VALUES(11, 'Jaru');
INSERT INTO cidade (id_estado, nome) VALUES(11, 'Ji-Paraná');
INSERT INTO cidade (id_estado, nome) VALUES(11, 'Machadinho D''Oeste');
INSERT INTO cidade (id_estado, nome) VALUES(11, 'Marco Rondon');
INSERT INTO cidade (id_estado, nome) VALUES(11, 'Ministro Andreazza');
INSERT INTO cidade (id_estado, nome) VALUES(11, 'Mirante da Serra');
INSERT INTO cidade (id_estado, nome) VALUES(11, 'Monte Negro');
INSERT INTO cidade (id_estado, nome) VALUES(11, 'Nova Brasilândia D''Oeste');
INSERT INTO cidade (id_estado, nome) VALUES(11, 'Nova Mamoré');
INSERT INTO cidade (id_estado, nome) VALUES(11, 'Nova União');
INSERT INTO cidade (id_estado, nome) VALUES(11, 'Nova Vida');
INSERT INTO cidade (id_estado, nome) VALUES(11, 'Novo Horizonte do Oeste');
INSERT INTO cidade (id_estado, nome) VALUES(11, 'Ouro Preto do Oeste');
INSERT INTO cidade (id_estado, nome) VALUES(11, 'Parecis');
INSERT INTO cidade (id_estado, nome) VALUES(11, 'Pedras Negras');
INSERT INTO cidade (id_estado, nome) VALUES(11, 'Pimenta Bueno');
INSERT INTO cidade (id_estado, nome) VALUES(11, 'Pimenteiras do Oeste');
INSERT INTO cidade (id_estado, nome) VALUES(11, 'Porto Velho');
INSERT INTO cidade (id_estado, nome) VALUES(11, 'Presidente Médici');
INSERT INTO cidade (id_estado, nome) VALUES(11, 'Primavera de Rondônia');
INSERT INTO cidade (id_estado, nome) VALUES(11, 'Príncipe da Beira');
INSERT INTO cidade (id_estado, nome) VALUES(11, 'Rio Crespo');
INSERT INTO cidade (id_estado, nome) VALUES(11, 'Riozinho');
INSERT INTO cidade (id_estado, nome) VALUES(11, 'Rolim de Moura');
INSERT INTO cidade (id_estado, nome) VALUES(11, 'Santa Luzia D''Oeste');
INSERT INTO cidade (id_estado, nome) VALUES(11, 'São Felipe D''Oeste');
INSERT INTO cidade (id_estado, nome) VALUES(11, 'São Francisco do Guaporé');
INSERT INTO cidade (id_estado, nome) VALUES(11, 'São Miguel do Guaporé');
INSERT INTO cidade (id_estado, nome) VALUES(11, 'Seringueiras');
INSERT INTO cidade (id_estado, nome) VALUES(11, 'Tabajara');
INSERT INTO cidade (id_estado, nome) VALUES(11, 'Teixeirópolis');
INSERT INTO cidade (id_estado, nome) VALUES(11, 'Theobroma');
INSERT INTO cidade (id_estado, nome) VALUES(11, 'Urupá');
INSERT INTO cidade (id_estado, nome) VALUES(11, 'Vale do Anari');
INSERT INTO cidade (id_estado, nome) VALUES(11, 'Vale do Paraíso');
INSERT INTO cidade (id_estado, nome) VALUES(11, 'Vila Extrema');
INSERT INTO cidade (id_estado, nome) VALUES(11, 'Vilhena');
INSERT INTO cidade (id_estado, nome) VALUES(11, 'Vista Alegre do Abunã');
INSERT INTO cidade (id_estado, nome) VALUES(12, 'Campinas');
INSERT INTO cidade (id_estado, nome) VALUES(24, 'EDUARDO GOMES');